### ISSUE TITLE
Would you mind share your use case?

### ISSUE THREAD

**Issue by NE-SmallTown** [adam-26/react-dom-html#1]
motivation, trade offs, thinkings, ... :)

**Comment by adam-26** [comment]
@NE-SmallTown, did you read the [package specific README file](https://github.com/adam-26/react-dom-html/blob/master/packages/react-dom-html/README.md)? 

It simplifies rendering React applications. Easy to switch from string -> stream rendering on the server, and allows you to use JSX/React components for boilerplate to improve code re-use.

If you have any more specific questions, please ask :)
